### ISSUE TITLE
Generates error with sbt 1.3.3

### ISSUE THREAD

**Issue by b-gyula** [tototoshi/sbt-slick-codegen-example#1]
D:\dev\trq\build.sbt:112: warning: lazy value slickCodegenSettings in object autoImport is deprecated: use enablePlugins(CodegenPlugin)
slickCodegenSettings
^
D:\dev\trq\build.sbt:116: error: `<+=` operator is removed. Try `lhs += { x.value }`
  or see http://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html.
sourceGenerators in Compile <+= slickCodegen
                            ^
[error] Type error in expression

**Comment by oeil2lynx** [comment]
As a workaround, you can write it like this in sbt 1.3.3 :

`Compile / sourceGenerators += slickCodegen`
